<?php
	if (!isset($_SESSION)) session_start();

	if (!function_exists("strtorandom")) {
		$APP_RootDir ??= str_repeat("../", substr_count($_SERVER["PHP_SELF"], "/"));
		require_once($APP_RootDir."private/script/function/utility.php");
		require_once($APP_RootDir."private/script/lib/TianTcl/various.php");
	}

	/**
	 * VirtualToken class for creating and managing virtual tokens based on a hash salt. This class provides methods for creating a token from a given number, reading the original number from a token, and resetting the hash salt. The token is generated by applying a mathematical transformation to the input number using the hash salt, and then encoding it in base36 format. The class also includes a method for generating a new random hash salt and storing it in the session.
	 * 
	 * @author TianTcl
	 */
	class VirtualToken {
		private $hashSalt;
		/**
		 * Constructor for the VirtualToken class. This method initializes the hash salt by checking if it is already set in the session. If the hash salt is not set or if the `$forceNewSalt` parameter is true, it generates a new random hash salt and stores it in the session. Otherwise, it retrieves the existing hash salt from the session and assigns it to the instance variable.
		 * 
		 * @param bool $forceNewSalt Optional parameter that determines whether to force the generation of a new hash salt. If set to true, a new hash salt will be generated regardless of whether one already exists in the session. If set to false (default), a new hash salt will only be generated if one does not already exist in the session.
		 */
		function __construct(bool $forceNewSalt=false) {
			if (empty(TianTcl::sessVar("hash_salt")) || $forceNewSalt) $this -> newHashSalt();
			else $this -> hashSalt = TianTcl::sessVar("hash_salt");
		}

		/**
		 * Generates a random salt value for hashing. The method generates a random integer between 1001 and 9999 using the built-in `rand()` function.
		 * 
		 * @return int The generated random salt value, which is an integer between 1001 and 9999.
		 */
		protected function generateRandomSalt(): int {
			return rand(1001, 9999);
		}
		/**
		 * Generates a new hash salt and stores it in the session. This method calls the `generateRandomSalt()` method to create a new random salt value, assigns it to the instance variable `$hashSalt`, and then stores it in the session using the `TianTcl::sessVar()` method with the key "hash_salt".
		 */
		final public function newHashSalt(): void {
			$this -> hashSalt = $this -> generateRandomSalt();
			TianTcl::sessVar("hash_salt", $this -> hashSalt);
		}
		/**
		 * Encrypts a given number into a virtual token using the hash salt. The method takes an integer or string input, applies a mathematical transformation using the hash salt, and then encodes the result in base36 format to create the token.
		 * 
		 * @param int|string $ID The input number to be encrypted into a virtual token. This can be either an integer or a string representation of a number.
		 * @return string|false The generated virtual token, which is a string representation of the transformed input, or false if the input is invalid.
		 */
		private function encryptNID(int|string $ID): string|false {
			if (!is_numeric($ID)) return false;
			return strtorandom(base_convert(((int)$ID + $this -> hashSalt) * $this -> hashSalt, 10, 36));
		}
		/**
		 * Decrypts a given virtual token back to the original number using the hash salt. The method takes a string input (the virtual token), decodes it from base36 format, applies the inverse mathematical transformation using the hash salt, and returns the original number as an integer. If the input token does not match the expected format, it returns an empty string.
		 * 
		 * @param string $ID The virtual token to be decrypted. This should be a string representation of the token generated by the `encryptNID()` method.
		 * @return int|false The original number that was encrypted into the virtual token, returned as an integer, or false if the input token is invalid or does not match the expected format.
		 */
		private function decryptNID(string $ID): int|false {
			if (!preg_match("/^[0-9A-Za-z]{4,}$/", $ID)) return false;
			return base_convert(strtolower($ID), 36, 10) / $this -> hashSalt - $this -> hashSalt;
		}

		/**
		 * Public method to create a virtual token from a given number. This method serves as an interface for generating a token, returning the corresponding virtual token as a string, or false if the input is invalid.
		 * 
		 * @param int|string $number The input number to be converted into a virtual token. This can be either an integer or a string representation of a number.
		 * @return string|false The generated virtual token as a string, or false if the input number is invalid.
		 */
		final public function create(int|string $number): string|false { return $this -> encryptNID($number); }
		/**
		 * Public method to read the original number from a given virtual token. This method serves as an interface for decrypting a token, returning the original number as an integer, or false if the input token is invalid.
		 * 
		 * @param string $str The virtual token to be decrypted. This should be a string representation of the token generated by the `create()` method.
		 * @return int|false The original number that was encrypted into the virtual token, returned as an integer, or false if the input token is invalid.
		 */
		final public function read(string $str): int|false { return $this -> decryptNID($str); }
		/**
		 * Alias: {@see newHashSalt}
		 */
		public function reset(): void { $this -> newHashSalt(); }

	} $vToken = new VirtualToken();
?>